name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore RadioSharp.App/RadioSharp.App.csproj

    - name: Build
      run: dotnet build RadioSharp.App/RadioSharp.App.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish RadioSharp.App/RadioSharp.App.csproj --configuration Release --no-restore --output publish

    - name: Create zip archive
      run: Compress-Archive -Path publish/* -DestinationPath publish/RadioSharp-App-${{ github.run_number }}.zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: RadioSharp-App-${{ github.run_number }}
        path: publish/RadioSharp-App-${{ github.run_number }}.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: RadioSharp-App-${{ github.run_number }}
          path: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RadioSharp-App-${{ github.run_number }}.zip
          asset_name: RadioSharp-App-${{ github.run_number }}.zip
          asset_content_type: application/zip
